### PR TITLE
Add more convenience wrappers: open(), eachline(), readline(), readlines()

### PR DESCRIPTION
**Pull request by nalimilan**

### CODE REVIEW

**Comment by ScottPJones** [comment]
Some problem with mktemp on Windows machines, but this looks nice!

**Comment by nalimilan** [comment]
Right, a file handle wasn't closed properly. I've also found out that `close` didn't call `close` on the wrapper stream, which means that `do open(path, enc) ...` didn't work. So I changed it to call `close`.

This is different from what `Base64EncodePipe` does. The alternative is to override the method for `open`, but I think I like this solution better, since I find it surprising that closing the stream is not enough to close the file handle. OTOH, maybe we need a way to close the `StringEncoder`/`StringDecoder` without closing the stream?

**Comment by ScottPJones** [comment]
Yes to being able to close `StringEncoder/StringDecoder` independently of the stream, because you may have a stream where you are using different encodings - you read in a marker that indicates that the next n bytes are Binary, then another marker shows that you have n bytes of UTF8, etc.
I think it would be nice to be able to have both, some convenient way of handling an entire file with a particular encoding, *and* be able to handle the harder cases like streams that have serialized data with different encodings in them (I do that all the time, in fact, in my packed database stuff).  I'll trust you to come up with a very nice, Julian API for that!

**Comment by nalimilan** [comment]
I think I've found a solution: I simply added a `closestream` field to `StringEncoder`/`StringDecoder`, which is set to `true` only from `open`. This is indeed the only place from which the user has no access to the underlying I/O stream (that's the whole point of this convenience API). It introduces a small inconsistency, but not a big deal and it's clearly documented.

**Comment by ScottPJones** [comment]
That sounds fine to me!

**Comment by nalimilan** [comment]
Let's go with that solution then. I'd like to tag a first release soon, before experimenting further with the `Encoding` type.

**Pull request merged**
